---
title: "Fitting Regression Model to Average Temperature"
author: "Vaibhav Bhatt"
date: "2026-02-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Read the data

##```{r}
# Insert here
##```
data = read.csv(file ='Chennai_1990_2022_Madras.csv',header = T)

str(data)

data$time = as.Date(data$time,format = "%d-%m-%Y")

str(data)

n = nrow(data)
data$tms = 1:n

data$tms = data$tms - mean(data$tms)

## Split the data into train and test

data_train = subset(data,time<=as.Date("2015-12-31"))
tail(data_train)

data_test = subset(data,time>as.Date("2015-12-31"))

head(data_test)

# Visualization

#```{r,fig=T}
plot(data_train$time[1:(3*365)],data_train$tavg[1:(3*365)],pch=20,xlab='',ylab = 'avg_temp')
#```

## Fit model 1

##$$
tavg = \beta_0 +\beta_1 t + \beta_2 \sin(\omega t)+\beta_3\cos(\omega t)+\varepsilon
##$$

where $\omega = \frac{2/pi}{P}$,$P=365$

omega = 2*pi/365

#n = nrow(data_train)
#data_train$tms = 1:n

#data_train$tms = data_train$tms - mean(data_train$tms)

## Model 1

mod1 = lm(tavg~tms+sin(omega*tms)+cos(omega*tms),data=data_train)
sum = summary(mod1)
sum
sigma=sum$sigma

data_train$fitted.values=NA

# Extracting values from model 1

data_train[rownames(mod1$model),'fitted.values']=mod1$fitted.values

plot(data_train$time[1:(3*365)],data_train$tavg[1:(3*365)],
      pch=20,col='grey',xlab=' ',ylab='avg_temp')

lines(data_train$time[1:(3*365)],data_train$fitted.values[1:(3*365)],col='red',lwd=2)

lines(data_train$time[1:(3*365)],data_train$fitted.values[1:(3*365)]-1.96*sigma,col='brown',lwd=2,lty=2)

lines(data_train$time[1:(3*365)],data_train$fitted.values[1:(3*365)]+1.96*sigma,col='brown',lwd=2,lty=2)

#### Do prediction in test data

#n = nrow(data_test)
#data_test$tms = 1:n

#data_test$tms = data_test$tms - mean(data_test$tms)

data_test$pred = predict(mod1,newdata=data_test)

plot(data_test$time,data_test$tavg,
      pch=20,col='grey',xlab=' ',ylab='avg_temp')

lines(data_test$time,data_test$pred,col='red',lwd=2)

lines(data_test$time,data_test$pred-1.96*sigma,col='brown',lwd=2,lty=2)

lines(data_test$time,data_test$pred+1.96*sigma,col='brown',lwd=2,lty=2)

